/**
 * GrainOverlay — Subtle paper-grain texture over the whole viewport.
 *
 * Implementation:
 * - Fixed, full-viewport, pointer-events-none, aria-hidden layer.
 * - Background-image = inline SVG data URI using SVG feTurbulence (fractal noise).
 *   No external binary asset is needed; the texture is generated by the browser.
 * - mix-blend-multiply makes it appear as warm paper grain over cream/light surfaces.
 * - Opacity ~0.05 — barely perceptible, never distracting.
 * - Static (no animation) → inherently prefers-reduced-motion safe.
 * - z-index 1 (above base background, below all content/UI which starts at z-auto).
 */

export function GrainOverlay() {
  // Inline SVG feTurbulence encoded as a data URI — no external file needed.
  const svgNoise = `<svg xmlns='http://www.w3.org/2000/svg' width='300' height='300'><filter id='n'><feTurbulence type='fractalNoise' baseFrequency='0.75' numOctaves='4' stitchTiles='stitch'/><feColorMatrix type='saturate' values='0'/></filter><rect width='300' height='300' filter='url(%23n)' opacity='1'/></svg>`;
  const dataUri = `url("data:image/svg+xml,${encodeURIComponent(svgNoise)}")`;

  return (
    <div
      aria-hidden="true"
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 1,
        pointerEvents: "none",
        backgroundImage: dataUri,
        backgroundRepeat: "repeat",
        backgroundSize: "300px 300px",
        opacity: 0.05,
        mixBlendMode: "multiply",
      }}
    />
  );
}
