/**
 * scripts/build-redirects.ts
 *
 * Reads the legacy site manifest and emits the 301 redirect artifacts:
 *   1. public/_redirects — Netlify CDN-native redirects (the delivery
 *      mechanism in production; zero runtime cost, no edge function).
 *      (Next 16's proxy.ts convention was tried first, but Turbopack-built
 *      middleware can't be bundled by @netlify/plugin-nextjs 5.x.)
 *   2. lib/redirects/redirects.generated.ts — the same map as a typed module
 *      for tests and any future non-Netlify runtime.
 *
 * Run: npm run redirects
 */

import fs from "fs";
import path from "path";
import { buildRedirectMap } from "../lib/redirects/build";

const CSV = path.resolve(process.cwd(), "data/source/all_naturals_site_manifest.csv");
const OUT = path.resolve(process.cwd(), "lib/redirects/redirects.generated.ts");

const csv = fs.readFileSync(CSV, "utf-8");
const map = buildRedirectMap(csv);

// Sort keys for a stable, review-friendly diff.
const sorted = Object.fromEntries(Object.entries(map).sort(([a], [b]) => a.localeCompare(b)));

const contents = `// AUTO-GENERATED by scripts/build-redirects.ts — do not edit by hand.
// Source: data/source/all_naturals_site_manifest.csv
// Regenerate: npm run redirects
export const REDIRECTS: Record<string, string> = ${JSON.stringify(sorted, null, 2)};
`;

fs.writeFileSync(OUT, contents);
console.log(`Wrote ${Object.keys(sorted).length} redirects → ${path.relative(process.cwd(), OUT)}`);

// Netlify CDN-native redirects — served before the Next.js handler.
const NETLIFY_OUT = path.resolve(process.cwd(), "public/_redirects");
const netlifyLines = [
  "# AUTO-GENERATED by scripts/build-redirects.ts — do not edit by hand.",
  "# 301s for legacy allnaturalscosmetics.com URLs. Regenerate: npm run redirects",
  ...Object.entries(sorted).map(([from, to]) => `${from} ${to} 301`),
];
fs.writeFileSync(NETLIFY_OUT, netlifyLines.join("\n") + "\n");
console.log(`Wrote ${Object.keys(sorted).length} redirects → ${path.relative(process.cwd(), NETLIFY_OUT)}`);
